### ISSUE TITLE
Repeated code

### ISSUE THREAD

**Issue by kgarlicki** [ratajrafal/ServiceNow-Switch-Instance#1]
https://github.com/ratajrafal/ServiceNow-Switch-Instance/blob/039ba4b252f0419fee680b4e4cd9b9ff01c27518/popup.js#L104

Just loop thru Instance configurations, the same code is used 10 times.

**Comment by ratajrafal** [comment]
sorry, weekend challenge, quick & dirty :) 
will improve soon

**Comment by ratajrafal** [comment]
`var myNewUrl =  tab.url.replace(/.*.service-now.com/, 'https://'+dropdown.value+'.service-now.com');`

replaces the instance name in service-now.com domain whatever it is, without checking. 
the previous code was definitely result of the Blue Monday effect.
