### ISSUE TITLE
Too many DOM manipulations

### ISSUE THREAD

**Issue by kgarlicki** [ratajrafal/ServiceNow-Switch-Instance#2]
https://github.com/ratajrafal/ServiceNow-Switch-Instance/blob/039ba4b252f0419fee680b4e4cd9b9ff01c27518/popup.js#L112

You are doing DOM change for every instance, that takes time.
Build the whole HTML and at the end modify the DOM.

**Comment by ratajrafal** [comment]
modified in v 1.0.3
